apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-oidc-cluster-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
